repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.3
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/4Catalyzer/fourmat
  rev: v0.4.2
  hooks:
    - id: fourmat
