repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.1
  hooks:
    - id: pyupgrade
      args: [--py39-plus]
- repo: https://github.com/4Catalyzer/fourmat
  rev: v0.11.1
  hooks:
    - id: fourmat
      additional_dependencies: [setuptools]
